//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UseMVVM.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_da" +
            "ta/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")]
        public string URI_CV19_Confirmed {
            get {
                return ((string)(this["URI_CV19_Confirmed"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_da" +
            "ta/csse_covid_19_time_series/time_series_covid19_deaths_global.csv")]
        public string URI_CV19_Death {
            get {
                return ((string)(this["URI_CV19_Death"]));
            }
            set {
                this["URI_CV19_Death"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_da" +
            "ta/csse_covid_19_time_series/time_series_covid19_recovered_global.csv")]
        public string URI_CV19_Recovered {
            get {
                return ((string)(this["URI_CV19_Recovered"]));
            }
            set {
                this["URI_CV19_Recovered"] = value;
            }
        }
    }
}
